SELECT * FROM mydatabase.mytable;
-- Q1 What is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) from mytable
group by gender;

-- Q2 which customer used a discount but still spent more than the average purchase amount ?
select customer_id ,purchase_amount from mytable 
where discount_applied='Yes' and purchase_amount>=(Select avg(purchase_amount) from mytable);

-- Q3 which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as rating from mytable
group by item_purchased
order by rating  desc
limit 5;


-- Q4 Compare the average Purchase Amounts between Standard and Express shipping?
select shipping_type,avg(purchase_amount) from mytable
where shipping_type in ('standard','Express')
group by shipping_type;


-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, 
count(customer_id) as total_customer,
avg(purchase_amount) as avg_spend,
sum(purchase_amount)as total_revenue from mytable
group by subscription_status;
-- (NO)

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(sum(case when discount_applied='Yes' then 1 else 0 end)/COUNT(*) * 100,2) AS discount_rate
from mytable
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customers into New , Returning and loyal based on their total number of previous purchasea and show the count of each segment.
with cte as(
select customer_id,previous_purchases,
case
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    End as customer_segment
from mytable
)
select customer_segment,count(*) as 'Number of Customers'
from cte
group by customer_segment;


-- Q8 What are the top 3 most purchased products within each category?
with cte as (
select category,item_purchased,count(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from mytable
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders from cte
where item_rank<=3;



-- Q9 Are the customers  who repeat buyers (more than 5 previous purchase) also likely to subscribed?
select subscription_status,count(customer_id) as repeat_buyers
from mytable
where previous_purchases >5
group by subscription_status;

-- Q10 What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) from mytable
group by age_group;



